### ISSUE TITLE
review: proposal to clarify in maintenance docs process to contact algo authors https://github.com/alan-turing-institute/sktime/pull/3154

### ISSUE THREAD

**Issue by aiwalter** [sktime/community-org#40]

**Comment by aiwalter** [comment]
I think we can close this? The linked PR is merged already?

**Comment by fkiraly** [comment]
Tony has opened an issue here where algo ownership is being changed/transferred
https://github.com/sktime/sktime/pull/3625

directly impacted by this discussion

**Comment by fkiraly** [comment]
action now on Franz: split PR into partitions as suggested by @aiwalter

**Comment by fkiraly** [comment]
Done:

https://github.com/sktime/sktime/pull/3675
https://github.com/sktime/sktime/pull/3676

To add detail, the partition suggested by @aiwalter was not minuted, but it was as above: algorithm maintainer changes were contentious, the rest he found non-contentious and fine to accept.

**Comment by fkiraly** [comment]
> I think we can close this? The linked PR is merged already?

The issue title referred to the wrong PR - it should be #3154, not #3155.
We clarified that in the Oct 25 CC meeting.

**Comment by fkiraly** [comment]
done, merged as 3676
