### ISSUE TITLE
[DOC] Consolidate communication channels and use slack over discord

### ISSUE THREAD

**Issue by lmmentel** [sktime/community-org#44]
#### Describe the issue linked to the documentation

This has been raised independently by two separate groups during brainstorming session in the dev days. It seems confusing that we have multiple channels for interacting with the community: slack, discord, github issues, github discussions ... It results in information not reaching interested members and posts being missed. We should consolidate the communication channels and have very clear recommendations for how to engage and where to find information.

There was a proposal to introduce a discord-slack bot to forward all the message to slack but there probably other actions that can be taken to improve the situation.

**Comment by fkiraly** [comment]
github actions is not a communication channel, it is a CI tool

**Comment by Lovkush-A** [comment]
One incremental step is to say we only use discord for video calls, not offline text communication. Any offline written discussion either on slack or github.

Not sure of benefit of github discussions over github issues. I have not used it much so I do not know.

Not clear how to make simple criteria for when to use github vs slack. Roughly 'technical discussion' on GitHub and everything else on slack.  But we also use github for public facing information (eg for gsoc application process). Not straightforward!

**Comment by GuzalBulatova** [comment]
I'm personally pro having slack only for all communication to be on Slack, but it's estimated to be ~500 euro per month for an org, and not exactly within our budget. So we'll have to have a platform for calls that anyone can join.

Maybe use Zoom for calls instead? They allow up to 100 attendees and I believe we haven't had an issue of more than 100 attendees for our regular meetings. The issue with that though is that someone has to set the call up and send everyone a link which is not as easy as to join a voice channel.

I personally have never used GitHub discussions either.

**Comment by miraep8** [comment]
Wow Slack is surprisingly expensive!!

For Zoom - if we want to go in that direction we could set up a standing link if desired - so that people can join the same link over and over again/whenever they want.  We do something like that for my lab. 

In the meantime/in line with what @Lovkush-A was suggesting - why don't we delete all non-meeting rooms on discord (eg the help desk?) as I think people who post for help there are simply not very visible.

**Comment by miraep8** [comment]
It might be worth noting that NumFocus has this on their website:

![image](https://user-images.githubusercontent.com/10511777/201190024-e9b97dc4-63ba-4216-94a8-15e38041051c.png)

I am not sure what they mean by "free slack team" (eg, would expect free slack pro, or free slack enterprise) but just wondering if it could be worth reaching out to them to see if they have a free slack license that they can share with us?  Especially if they have an enterprise license, which should support unlimited workspaces.

**Comment by fkiraly** [comment]
slack has now been deprecated in favour of discord.
