### ISSUE TITLE
Polling System for Community Council and Elections

### ISSUE THREAD

**Issue by janasberger** [sktime/community-org#55]
for consideration, for temporary (transition council) and permanent adoption (post-election, tbc)
## Discussions for the Polling System
We are looking into online voting and decision making systems. 

Requirements are:

- Anonymous
- Polling system for decisions in community council, frequent decision-making
- Elections for board with external contributor voters, not frequent

Discussed Options are:

- SecurePoll (WikiTech): Documentation: [https://wikitech.wikimedia.org/wiki/SecurePoll](url); [https://www.mediawiki.org/wiki/Extension:SecurePoll](url)
The SecurePoll extension is a special page extension for Wikipedia for elections, polls and surveys. 
Unfortunately, it is not available for general use - [https://meta.wikimedia.org/wiki/SecurePoll](url)
- easypoll.bot: Discord Bot, Website: [https://easypoll.bot](url)

Please leave any comments regarding the options and any additional systems we could consider here.

**Comment by fkiraly** [comment]
another option we'd previously used is the anonymous polling tool in slack, but I believe that has been restricted to max 100 votes a month. This is close to the total of votes we would see at the current pace, and is lower than what we'd expect of elections.

Further, one would need to create a channel for each set of voters.

Question is, are the following requirements:

* not seeing the state of the vote while it's ongoing
* 1 big (100s?) vote per year, 20 (dozen or so) small votes per month

**Comment by JonathanBechtel** [comment]
I actually like easypoll -- don't see why it wouldn't work and strikes me as the path of least resistance for conducting online polls.  I need to have some permissions to test it out, but it strikes me as preferable to software that's distinct from discord itself.

**Comment by fkiraly** [comment]
Update: we've trialled easypoll and it seems to work for simple votes.

Although it is not yet fully clear how we would audit the results, or restrict by eligibility, for applicability in votes or elections.

Right now the procedure seems to be, the one person who sets up the vote reads out the results. That is not "audit safe" - we need ways to check:

* the final result printed out to the electorate, not just to the vote setter
* a verifiable check that everyone voted at most once, ad oly eligile persons voted

**Comment by JonathanBechtel** [comment]
To add comments here:  I think easypoll is now the default way of performing polls, and we should consider this issue closed, since we've successfully held a few polls.
